export const GET_ALL_NOTES = "GET_ALL_NOTES";
export const ADD_NOTE = "ADD_NOTE";
export const DELETE_NOTE = "DELETE_NOTE";
export const UPDATE_NOTE = "UPDATE_NOTE";
export const NOTE_SELECTED = "NOTE_SELECTED";
export const ADD_NOTE_DESCRIPTION = "ADD_NOTE_DESCRIPTION";
export const DELETE_NOTE_DESCRIPTION = "DELETE_NOTE_DESCRIPTION";
export const FILTER_NOTES = "FILTER_NOTES";
